create
user filmorate-Nikita superuser;
alter
user filmorate-Nikita password 'filmorate';
create
database filmorate with owner filmorate-Nikita;


CREATE TABLE film_mpa
(
    mpa_id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(32)
);

CREATE TABLE film
(
    film_id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(64) NOT NULL,
    description     varchar(200),
    release_date    timestamp,
    duration        integer,
    mpa_id          integer REFERENCES film_mpa (mpa_id)
);


CREATE TABLE genre
(
    genre_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           varchar(32) NOT NULL
);

CREATE TABLE film_genre
(
    film_id        integer REFERENCES film (film_id),
    genre_id       integer REFERENCES genre (genre_id)
);

CREATE TABLE user_filmorate
(
    user_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          varchar(64),
    login          varchar(64),
    name           varchar(64),
    birthday       timestamp
);

CREATE TABLE film_likes
(
    film_id        integer REFERENCES film (film_id),
    user_id        integer REFERENCES user_filmorate (user_id)
);

CREATE TABLE friends
(
    user_id        integer REFERENCES user_filmorate (user_id),
    friend_id      integer REFERENCES user_filmorate (user_id)
);

INSERT INTO genre (name)
VALUES ('Комедия');
INSERT INTO genre (name)
VALUES ('Драма');
INSERT INTO genre (name)
VALUES ('Мультфильм');
INSERT INTO genre (name)
VALUES ('Триллер');
INSERT INTO genre (name)
VALUES ('Документальный');
INSERT INTO genre (name)
VALUES ('Боевик');

INSERT INTO film_mpa (name)
VALUES ('G');
INSERT INTO film_mpa (name)
VALUES ('PG');
INSERT INTO film_mpa (name)
VALUES ('PG-13');
INSERT INTO film_mpa (name)
VALUES ('R');
INSERT INTO film_mpa (name)
VALUES ('NC-17');